### ISSUE TITLE
kex_exchange_identification: Connection closed by remote host

### ISSUE THREAD

**Issue by JonasChengAsus** [antoniomika/sish#122] opened 2020-08-04 04:01 UTC
I'm evaluating replacement of existing ngrok, however I encounter error.

Here is my testing environment

1. Sish Server, which host sish service in Azure VM and start with command.

```console
sudo docker run -d --rm --name sish \
  -v `pwd`/ssl:/ssl \
  -v `pwd`/keys:/keys \
  -v `pwd`/pubkeys:/pubkeys \
  # also tried latest version
  --net=host antoniomika/sish:v1.0.10 \
  --ssh-address=:2222 \
  --http-address=:80 \
  --https-address=:443 \
  --https=true \
  --https-certificate-directory=/ssl \
  --authentication-keys-directory=/pubkeys \
  --private-key-location=/keys/ssh_key \
  --bind-random-ports=false \
  --domain=sish.jonasc.dev \
  --debug=true
```

2. Target host, which simulate a client behind NAT.
     To compare ngrok and sish, I start ngrok.service and ssh command

```console
ssh -p 2222 -R localhost:22 sish.jonasc.dev

The authenticity of host '[sish.jonasc.dev]:2222 ([138.91.40.243]:2222)' can't be established.
ED25519 key fingerprint is SHA256:pI0c5nUORoAw4CUy4NcrMQlQJvpwcN316+AmJ5B7+Ew.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '[sish.jonasc.dev]:2222,[138.91.40.243]:2222' (ED25519) to the list of known hosts.
Press Ctrl-C to close the session.

The TCP port :22 is unavailable. Assigning a random port.
Starting SSH Forwarding service for tcp:22. Forwarded connections can be accessed via the following methods:
TCP: sish.jonasc.dev:41729
```

3. My laptop, which I intend to ssh login from

I can login via ngrok, however can't via sish.

```console
ssh -vvv -i ~/.ssh/id_rsa jonas_cheng@sish.jonasc.dev -p 41729

OpenSSH_8.1p1, LibreSSL 2.7.3
debug1: Reading configuration data /Users/jonas/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 47: Applying options for *
debug1: Connecting to sish.jonasc.dev port 41729.
debug1: Connection established.
debug1: identity file /Users/jonas/.ssh/id_rsa type 0
debug1: identity file /Users/jonas/.ssh/id_rsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.1
kex_exchange_identification: Connection closed by remote host
```

I google similar error, however most of solution does not works to me.
As I believe target host sshd configuration works for ngrok, and it should work for sish too.
Could you light me what mistake I made? Thanks!

**Comment by JonasChengAsus** [comment] 2020-08-04 06:37
Btw, it can be easy to repro with a simple vagrant

```yml
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 16384
    v.cpus = 2
  end

  # Specify your hostname if you like
  # config.vm.hostname = "name"
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.network "private_network", type: "dhcp"
end

```

**Comment by antoniomika** [comment] 2020-08-04 22:09
Interesting! I was able to reproduce this locally using the above steps. As a simple work around, you can explicitly set the port. For your usecase, that can either just be `-R 22:localhost:22` or to get a random port `-R 0:localhost:22`. I'm still looking into why this happens though.

**Comment by JonasChengAsus** [comment] 2020-08-05 00:43
Thanks @antoniomika for work around, and I can ssh login to target host now however the connection will be closed shortly, the connection does not last over 10 sec with the following error message. Do you have any idea to work around this? Thanks!

```console
jonas_cheng@vagrant:~$ debug3: send packet: type 1
debug1: channel 0: free: client-session, nchannels 1
debug3: channel 0: status: The following connections are open:
  #0 client-session (t4 r0 i0/0 o0/0 e[write]/0 fd 6/7/8 sock -1 cc -1)

debug3: fd 1 is not O_NONBLOCK
Connection to sish.jonasc.dev closed by remote host.
Connection to sish.jonasc.dev closed.
Transferred: sent 4072, received 4220 bytes, in 7.0 seconds
Bytes per second: sent 579.4, received 600.4
debug1: Exit status -1
```

**Comment by antoniomika** [comment] 2020-08-05 00:45
Yep! Take a look at this comment:

https://github.com/antoniomika/sish/issues/113#issuecomment-658917828

**Comment by JonasChengAsus** [comment] 2020-08-05 00:53
> Yep! Take a look at this comment:
> 
> [#113 (comment)](https://github.com/antoniomika/sish/issues/113#issuecomment-658917828)

Thanks! work perfectly now.

**Comment by mark-sch** [comment] 2020-10-06 11:42
I am facing the same/similar issue, accessing a remote port bound SSH service is impossible. While connection to the remote with an TCP alias, the error is:

Connection to xyz closed by remote host.
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535

Any idea what can be tested/configured?

**Comment by antoniomika** [comment] 2020-10-06 12:30
Hmm, could you include what ssh command you are using? Also some logs from sish would be helpful!

**Comment by mark-sch** [comment] 2020-10-06 13:05
Thx for the quick reply, I disabled auth temporarily now for testing. Any attempt to connect to the markssh alias on port 22 fails so far. I wonder why a http binding on port 2020 is created for the tcp:22 service?

ssh -p 2222 -R mark:80:localhost:7070 -R markssh:22:localhost:22 ns2.think5.de
Press Ctrl-C to close the session.

Starting SSH Forwarding service for tcp:22. Forwarded connections can be accessed via the following methods:
HTTP: http://markssh.sunny5.de:2020

Starting SSH Forwarding service for http:80. Forwarded connections can be accessed via the following methods:
HTTP: http://mark.sunny5.de:2020

**Comment by mark-sch** [comment] 2020-10-06 16:14
Awesome, you are the man :-) Works now except the connection is dropped after a few seconds. What is your suggested way to fix this?

**Comment by mark-sch** [comment] 2020-10-06 18:10
Adding `stdin_open: true` and `tty: true` to the docker-compose.yml kept the connection open. But not exactly sure about the impact, so I added `--idle-connection-timeout=60m` now, this should fit the needs in most cases.

**Comment by antoniomika** [comment] 2020-10-06 20:21
Take a look at this whole issue, I think the same fix above should work for you!

**Comment by antoniomika** [comment] 2020-10-24 03:28
I actually just confirmed this isn't an issue with sish (yay!). It looks like this happens with SSH and is expected. Taken from SSH manpage:
```
if no explicit destination was specified, ssh will act as a SOCKS 4/5 proxy and forward connections to the destinations requested by the remote SOCKS client
```
sish doesn't support SOCKS, which explains why things don't work as we think they should!

**Closed by antoniomika** 2020-10-24 03:28 UTC
Labels: bug
