### ISSUE TITLE
Local port forward (-L) from sish

### ISSUE THREAD

**Issue by blop** [antoniomika/sish#138] opened 2020-10-06 15:48 UTC
Hello!

I have another question ;-)

When publishing TCP ports with aliases to sish, I can local forward these from another machine after.

Also, if the 2nd ssh client is not asking any remote port forward (-R) the connection is considered "unbound" and is terminated according to --cleanup-unbound, which is expected I guess.

However, the local port is working for only 1 tcp connection.
As soon as I disconnect from the local port, sish terminates the whole session of the 2nd ssh client.

Is this expected as well ?
Or is there a workaround ?

Thank you!
Regards,

Olivier

**Comment by antoniomika** [comment] 2021-11-07 19:39
Hey @blop,

Can I have some SSH commands to reproduce this/understand what you're expecting? Sorry for the delay between getting to this. My life has been busy and sish unfortunately hasn't been a priority but I'm trying to change that :)

You'll see some progress on the other features you mentioned over the next day!

**Comment by blop** [comment] 2021-11-08 13:19
Hello @antoniomika,

Thanks for your hard work on sish ;-)

The local port fortward -L is described in the SSH man page.
The idea is to make some TCP port open on the target available locally.

In the Sish context, it can be used to extend a tunnel further, or make it available to clients that cannot access sish directly.

Currently, it's working only partially.

Small example :

@ Machine A

- Service running on port 80

- A first SSH client which publish that service on sish (using a TCP alias to keep it private) : 
`ssh -R myalias:1234:localhost:80` sish.server`

@ Machine B

- A second SSH client connects to sish and wants to extend that tunnel with another one in the opposite direction, publishing the service locally : 
`ssh -L 0.0.0.0:80:myalias:1234 sish.server`

Issue #1 is that this command is not working because we get "No forwarding requests sent. Closing connection." after ~5 seconds.
The workaround is to publish some random useless service in addition, like this : 
`ssh -L 0.0.0.0:80:myalias:1234 -R foo:2345:localhost:2345 sish.server`

@ Machine C

- A service client on machine C can now connects to the machine B on port 80 and access the HTTP service from machine A directly, without having any access to sish.
`curl -v machineB/`

Issue #2 is that right after the curl finishes, the second SSH client is terminating for some reason, we have to start it again before another HTTP request can be made.

Log of the sish server for the 3 calls : 
`
2021/11/08 - 13:12:06 | Accepted SSH connection for: 10.11.12.13:2780
2021/11/08 - 13:12:06 | Login attempt: 10.11.12.13:2780, user ov key: ssh-rsa ***
2021/11/08 - 13:12:06 | TCP Alias forwarding started: myalias:1234 -> /tmp/10.11.12.13:2780:1234657440039 for client: 10.11.12.13:2780

2021/11/08 - 13:12:15 | Accepted SSH connection for: 10.11.12.13:1025
2021/11/08 - 13:12:16 | Login attempt: 10.11.12.13:1025, user ov key: ssh-rsa ***
2021/11/08 - 13:12:16 | TCP Alias forwarding started: foo:2345 -> /tmp/10.11.12.13:1025:2345461572186 for client: 10.11.12.13:1025

2021/11/08 - 13:12:21 | Accepted connection from 10.11.12.13:1025 -> myalias:1234
2021/11/08 - 13:12:21 | Closed SSH connection for: 10.11.12.13:1025 user: ov
`

I know it's an odd use case but I feel like not much is missing to make it work ;-)
Also, the standard SSH client always had the capability of creating TCP tunnels that work in either directions, so I feel sish should support that as well.

Let me know if you need me to perform other tests.

**Comment by antoniomika** [comment] 2021-11-09 03:23
I have this working over in #198! There's a distinction between two commands now because SSH does not send anything to the server when setting up a local forward until a forward request comes through. To make this work, set `--cleanup-unbound` to false (the new default). There's also a new flag `--cleanup-unauthed` so that we remove unauthenticated connections. Just note that on public instances, not having `--cleanup-unbound` can retain a lot of bot connections!

**Comment by blop** [comment] 2021-11-09 07:57
Great news ;-) I can't wait to test it!
I assume the "cleanup-unbound to false" fixes both issues mentioned above ?
The goal is obviously to be able to handle more than one connection to the local forward.

**Comment by antoniomika** [comment] 2021-11-09 10:11
Correct! There was also a piece of code that was closing the session when data finished copying which shouldn't be the case.

**Closed** 2021-11-12 00:38 UTC
Labels: feature-request
