### ISSUE TITLE
Questions and bugs on the way to 1.0

### ISSUE THREAD

**Issue by andreasunterhuber** [antoniomika/sish#90] opened 2020-05-25 17:33 UTC
Hi @antoniomika - your tool is great. But current release throwing me an error: 

```
2020/05/25 - 17:32:56 | Starting SSH service on address: localhost:2222
2020/05/25 - 17:32:56 | ssh: invalid openssh private key format
```

Getting this in latest docker and standalone binary. 
How to create correct keys and folder structure for new version?

**Comment by antoniomika** [comment] 2020-05-25 17:36
@andreasunterhuber is this using the `:latest` docker tag or the `v1.0` tags? This issue should be fixed in the v1.0 tags, but will likely require regenerating an OPENSSH hostkey. Before, we were using AES encrypted pem blocks, which would prevent using keys generated with ssh-keygen. We've since moved to using the native openssh key rfc which encrypts the key as part of the block.

**Comment by andreasunterhuber** [comment] 2020-05-25 17:59
@antoniomika thanks for the quick answer. Tried with `v1.0-work` tag but did not work either. 

Generated the keys by `ssh-keygen`, set the same password you use for default (`S3Cr3tP4$$phrAsE`) and moved: 
* Key to: deploy/keys/ssh_key
* Pub to: deploy/pubkeys/ssh_key.pub

Getting: 
```
./sish_binary
2020/05/25 - 17:56:24 | Starting SSH service on address: localhost:2222
panic: html/template: pattern matches no files: `templates/*`

goroutine 10 [running]:
html/template.Must(...)
	/usr/local/go/src/html/template/template.go:372
github.com/gin-gonic/gin.(*Engine).LoadHTMLGlob(0xc0000d03c0, 0xdbe787, 0xb)
	/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:185 +0x362
github.com/antoniomika/sish/httpmuxer.Start(0xc000080500)
	/app/httpmuxer/httpmuxer.go:37 +0x134
created by github.com/antoniomika/sish/sshmuxer.Start
	/app/sshmuxer/sshmuxer.go:66 +0x559
```

Version info: 
```
Version: v1.0-work
Commit: af01eee21e02cbf988265a1bfc870e73023b89bc
Date: 2020-05-23T19:17:56Z
```

**Comment by antoniomika** [comment] 2020-05-25 18:05
@andreasunterhuber sish needs to be run within the same directory that you download the binary from. It needs the `templates/` directory for the web interface. If the host key is generated with ssh-keygen, it should definitely be supported.

**Comment by andreasunterhuber** [comment] 2020-05-25 18:32
@antoniomika finally works ... 😍  Sorry - the templates was really understandable by the error message!

Just wondering ... starting the server like: 
`./sish_binary --admin-console --log-to-client --tcp-load-balancer -d router.example.com -a 0.0.0.0:2222 --bind-random-subdomains-length 4 --bind-random-subdomains false`  works fine. 

But connecting as a client like: 
`ssh -p 2222 -R andreas:80:localhost:4000 router.example.com` tells me: 

```
The subdomain andreas.router.example.com is unavailable. Assigning a random subdomain.
Starting SSH Forwarding service for http:80. Forwarded connections can be accessed via the following methods:
HTTP: http://jdbm.router.example.com
``` 

Why is the subdomain ignored?

**Comment by antoniomika** [comment] 2020-05-25 18:35
Hmm, it actually shouldn't be... Let me see if I can reproduce on my end. What is the exact version you downloaded?

**Comment by andreasunterhuber** [comment] 2020-05-25 18:36
@antoniomika it's the following: 
```
Version: v1.0-work
Commit: af01eee21e02cbf988265a1bfc870e73023b89bc
Date: 2020-05-23T19:17:56Z
```

**Comment by antoniomika** [comment] 2020-05-25 18:39
@andreasunterhuber try using `--bind-random-subdomains=false` as the param (= between the flag and value). I think this is a limitation of cobra as it pertains to bool flags!

**Comment by andreasunterhuber** [comment] 2020-05-25 19:09
@antoniomika works! 👍 
Hopefully last question: you have an idea why 

```
ssh -p 2222 -R andreas:80:localhost:4000 router.example.com
```

causes: 
```
curl -i http://andreas.router.example.com
curl: (7) Failed to connect to andreas.router.example.com port 80: Connection refused
```
With absolutely no info in log (server and client).

**Comment by antoniomika** [comment] 2020-05-25 19:12
@andreasunterhuber best guess is you need to set the interface sish listens on. By default it listens to `localhost:80` but you may want to set it to `:80` so that it'll listen on all interfaces.

**Comment by andreasunterhuber** [comment] 2020-05-25 20:53
@antoniomika your guess was absolutely right! Running: 
`./sish --log-to-client --tcp-load-balancer -d router.example.com -a 0.0.0.0:2222 --bind-random-subdomains-length 4 --bind-random-subdomains=false -i ":80"` works as expected. Really nice work 👍 

Seems to be a bug: adding `--admin-console` to the server arguments causes 500 error on each request: 

```
2020/05/25 20:45:53 [Recovery] 2020/05/25 - 20:45:53 panic recovered:
runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:212 (0x449259)
/usr/local/go/src/runtime/signal_unix.go:695 (0x4490a8)
/app/httpmuxer/proxy.go:101 (0xbe17a7)
/usr/local/go/src/net/http/httputil/reverseproxy.go:177 (0xaa32d0)
/usr/local/go/src/net/http/httputil/reverseproxy.go:278 (0xaa3776)
/go/pkg/mod/github.com/antoniomika/oxy@v1.1.1-0.20200517194743-bedd7c62c77e/forward/fwd.go:564 (0xad146f)
/go/pkg/mod/github.com/antoniomika/oxy@v1.1.1-0.20200517194743-bedd7c62c77e/forward/fwd.go:292 (0xace979)
/go/pkg/mod/github.com/antoniomika/oxy@v1.1.1-0.20200517194743-bedd7c62c77e/roundrobin/rr.go:147 (0x76b4ac)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/utils.go:48 (0xabaaef)
/app/httpmuxer/httpmuxer.go:146 (0xbe001e)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xaa730a)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/recovery.go:83 (0xaba76f)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xaa730a)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/logger.go:241 (0xab98a0)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xaa730a)
/app/httpmuxer/httpmuxer.go:48 (0xbdeeba)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xaa730a)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:445 (0xab0ec7)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:438 (0xab0b22)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 (0xab04cc)
/usr/local/go/src/net/http/server.go:2807 (0x6ebe82)
/usr/local/go/src/net/http/server.go:1895 (0x6e77fb)
/usr/local/go/src/runtime/asm_amd64.s:1373 (0x462f50)
```

I will move this into a new issue if you want ;)

**Comment by antoniomika** [comment] 2020-05-26 00:33
@andreasunterhuber can you share the full command you're testing?

**Comment by antoniomika** [comment] 2020-05-26 03:33
@andreasunterhuber can you also share an example request that you are making and what the ssh command you are using is?

**Comment by andreasunterhuber** [comment] 2020-05-26 08:58
@antoniomika OK, using the most recent version (tag `v1.0-work`) 
```
Version: v1.0.0-rc3-SNAPSHOT-3a25ead
Commit: 3a25ead6137cedb7b540c3b064d6adbc0eb8f447
Date: 2020-05-26T08:43:43Z
```

## Using: 
**Server**: 
`sish --log-to-client --tcp-load-balancer -d router.example.com -a 0.0.0.0:2222 --bind-random-subdomains-length 4 --bind-random-subdomains=false -i ":80" -r="https://www.example.com" --admin-console`

**Client**: 
`ssh -p 2222 -R andreas:80:localhost:3000 router.example.com`

## Result:

```
2020/05/26 - 08:53:04 | andreas.router.example.com | 500 |   15.635048ms |  11.222.244.222 | GET      /assets/i18n/translations.self-6a3cf5192354f71615ac51034b3e97c20eda99643fcaf5bbe6d41ad59bd12167.js?body=1

2020/05/26 08:53:04 [Recovery] 2020/05/26 - 08:53:04 panic recovered:
runtime error: invalid memory address or nil pointer dereference
/usr/local/Cellar/go/1.14.3/libexec/src/runtime/panic.go:212 (0x449259)
/usr/local/Cellar/go/1.14.3/libexec/src/runtime/signal_unix.go:695 (0x4490a8)
/Users/Andreas/PRO/EXT_sish/httpmuxer/proxy.go:101 (0xbe1807)
/usr/local/Cellar/go/1.14.3/libexec/src/net/http/httputil/reverseproxy.go:177 (0xaa32d0)
/usr/local/Cellar/go/1.14.3/libexec/src/net/http/httputil/reverseproxy.go:278 (0xaa3776)
/Users/Andreas/go/pkg/mod/github.com/antoniomika/oxy@v1.1.1-0.20200517194743-bedd7c62c77e/forward/fwd.go:564 (0xad146f)
/Users/Andreas/go/pkg/mod/github.com/antoniomika/oxy@v1.1.1-0.20200517194743-bedd7c62c77e/forward/fwd.go:292 (0xace979)
/Users/Andreas/go/pkg/mod/github.com/antoniomika/oxy@v1.1.1-0.20200517194743-bedd7c62c77e/roundrobin/rr.go:147 (0x76b4ac)
/Users/Andreas/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/utils.go:48 (0xabaaef)
/Users/Andreas/PRO/EXT_sish/httpmuxer/httpmuxer.go:150 (0xbe007e)
/Users/Andreas/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xaa730a)
/Users/Andreas/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/recovery.go:83 (0xaba76f)
/Users/Andreas/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xaa730a)
/Users/Andreas/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/logger.go:241 (0xab98a0)
/Users/Andreas/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xaa730a)
/Users/Andreas/PRO/EXT_sish/httpmuxer/httpmuxer.go:52 (0xbdef1a)
/Users/Andreas/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xaa730a)
/Users/Andreas/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:445 (0xab0ec7)
/Users/Andreas/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:438 (0xab0b22)
/Users/Andreas/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 (0xab04cc)
/usr/local/Cellar/go/1.14.3/libexec/src/net/http/server.go:2807 (0x6ebe82)
/usr/local/Cellar/go/1.14.3/libexec/src/net/http/server.go:1895 (0x6e77fb)
/usr/local/Cellar/go/1.14.3/libexec/src/runtime/asm_amd64.s:1373 (0x462f50)
```

## Possible solution
Remove the `--admin-console` from server command.

**Comment by antoniomika** [comment] 2020-05-26 14:24
@andreasunterhuber this looks like it's actually occurring because there is no endpoint connected to the tunnel (there's nothing running on `localhost:3000`. That being said, a gateway issue should throw a 502 and I have a fix for that. In the meantime, admin console should work as long as the endpoint that is forwarded in the tunnel is connected

**Comment by andreasunterhuber** [comment] 2020-05-26 15:14
@antoniomika `localhost:3000` endpoint was active 🤔 Would be happy to test again if you have a new release. In the meantime we started a extended test. So far: ... compliment! It works very good! 💪

**Comment by antoniomika** [comment] 2020-05-26 15:40
@andreasunterhuber interesting, that's the only way I was able to reproduce it! Regardless, there is a new rc here: https://github.com/antoniomika/sish/releases/tag/v1.0.0-rc4 . Can you give that a go and report back?

**Comment by andreasunterhuber** [comment] 2020-05-27 08:57
@antoniomika last commit is tested and works 👍 Perfect! We start now a long term test on a dedicated server. I will report you, if we detect something!

**Comment by antoniomika** [comment] 2020-05-27 11:51
@andreasunterhuber glad to hear and thanks! I'll close this issue now and if you have anymore, feel free to open a new one!

**Closed by antoniomika** 2020-05-27 11:51 UTC
