### ISSUE TITLE
Problem with locking named domain by sish

### ISSUE THREAD

**Issue by fork04** [antoniomika/sish#83] opened 2020-04-27 10:56 UTC
Apr 22 21:52:36 srvub01 autossh[35368]: Starting SSH Fowarding service for http:80. Forwarded connections can be accessed via the following methods:
Apr 22 21:52:36 srvub01 autossh[35368]: HTTP: http://callcrm.foo.net
Apr 22 21:52:36 srvub01 autossh[35368]: HTTPS: https://callcrm.foo.net
Apr 22 21:52:36 srvub01 autossh[35368]: [1B blob data]
Apr 23 12:31:51 srvub01 autossh[35368]: Connection to foo.net closed by remote host.
Apr 23 12:31:51 srvub01 autossh[35368]: ssh exited with error status 255; restarting ssh
Apr 23 12:31:51 srvub01 autossh[35368]: starting ssh (count 36)
Apr 23 12:31:51 srvub01 autossh[35368]: ssh child pid is 24341
Apr 23 12:31:51 srvub01 autossh[35368]: Pseudo-terminal will not be allocated because stdin is not a terminal.
Apr 23 12:31:51 srvub01 autossh[35368]: Press Ctrl-C to close the session.
Apr 23 12:31:51 srvub01 autossh[35368]: [1B blob data]
Apr 23 12:31:51 srvub01 autossh[35368]: The subdomain callcrm.foo.net is unavailable. Assigning a random subdomain.
Apr 23 12:31:51 srvub01 autossh[35368]: Starting SSH Fowarding service for http:80. Forwarded connections can be accessed via the following methods:
Apr 23 12:31:51 srvub01 autossh[35368]: HTTP: http://zcz.foo.net
Apr 23 12:31:51 srvub01 autossh[35368]: HTTPS: https://zcz.foo.net
Apr 23 12:31:51 srvub01 autossh[35368]: [1B blob data]

**Comment by brzezinol** [comment] 2020-04-27 12:53
Hi, we have this problem mostly with windows openssh clients. 
But last time it started appearing with linux autossh clients too.

**Comment by antoniomika** [comment] 2020-04-30 00:09
Interesting. What do you have your timeout settings applied at @brzezinol and @fork04?

**Comment by fork04** [comment] 2020-04-30 10:55
So, default 5 sec. Here is ours startup file:
docker run -itd --restart always --name sish \
  -v ~/sish/ssl:/ssl \
  -v ~/sish/keys:/keys \
  -v ~/sish/pubkeys:/pubkeys \
  -v ~/sish/tmp:/tmp \
  --net=host antoniomika/sish:latest \
  -sish.addr=:2222 \
  -sish.https=:443 \
  -sish.http=:80 \
  -sish.httpsenabled=true \
  -sish.httpspems=/ssl \
  -sish.keysdir=/pubkeys \
  -sish.pkloc=/keys/ssh_key \
  -sish.bindrandom=false \
  -sish.forcerandomsubdomain=false \
  -sish.domain "foo.net" \
  -sish.usegeodb=false \
  -sish.redirectroot=false \
  -sish.adminenabled=true \
  -sish.admintoken "xxx" \
  -sish.serviceconsoleenabled=true \
  -sish.serviceconsoletoken "xxx"

**Comment by antoniomika** [comment] 2020-05-03 03:02
@fork04 can you try enabling the `-sish.pingclient` flag and see what that does for this? The reason this lock happens is because sish things the previous connection is still alive.

**Comment by antoniomika** [comment] 2020-05-17 22:30
Fixed this issue in #85. More or less the issue is fixed by enabling client pings, but you need to find the interval and idle timeout that works best for you. The defaults should work well for most usecases but may need to be adjusted for connections that don't implement pings/other keep alive messages.

**Closed by antoniomika** 2020-05-17 22:30 UTC
